#!/usr/bin/env python3
from pathlib import Path
import csv,hashlib

ROOT=Path(__file__).resolve().parents[1]
AUDIT=ROOT/"data/metadata/E4D1D_2019_runtime/CPS_ASEC/E4A2B_cps_full_weight_bridge_audit.txt"
SUMMARY=ROOT/"data/metadata/E4D1D_2019_runtime/CPS_ASEC/E4A2B_cps_full_weight_bridge_summary.tsv"

def rows(p):
    with p.open("r",encoding="utf-8",newline="") as f:
        return list(csv.DictReader(f,delimiter="\t"))

assert AUDIT.is_file()
assert SUMMARY.is_file()
text=AUDIT.read_text(encoding="utf-8")

required=[
 "CPS_MAIN_WEIGHT_VALUES_PARSED=1",
 "CPS_PWWGT0_VALUES_PARSED=1",
 "CPS_PWWGT1_160_VALUES_PARSED=0",
 "CPS_I_VALUES_READ=0",
 "SCF_K_D_VALUES_READ=0",
 "DIMENSIONALITY_OUTCOMES_OPENED=0",
 "CPS_ELIGIBLE_HOUSEHOLD_EXACTLY_ONE_REFERENCE=PASS",
 "CPS_REFERENCE_PERSON_PPPOS_41=PASS",
 "CPS_REPLICATE_LRECL_1456_VALUESIDE=PASS",
 "CPS_REFERENCE_PERSON_REPLICATE_MATCH=PASS",
 "CPS_PWWGT0_OFFICIAL_SUM_CHECK=PASS",
 "CPS_HSUP_WGT_MARSUPWT_EXACT_IDENTITY=PASS",
 "CPS_PWWGT0_MARSUPWT_TOLERANCE=0.0050",
 "CPS_PWWGT0_MARSUPWT_PRECISION_BRIDGE=PASS",
 "CPS_HOUSEHOLD_FULL_WEIGHT_BRIDGE=PASS",
 "CPS_WEIGHT_VALUE_IDENTITY_TEST_PERFORMED=1",
 "I_VALUES_OPEN_AUTHORIZED=0",
 "I_EMPIRICALLY_TESTED=0",
 "REAL_INFLATION_ESTIMATION_AUTHORIZED=0",
 "FINAL_SCALAR_AUTHORIZED=0",
 "E4A2B_WEIGHT_BRIDGE_AUDIT=PASS",
 "E4D1D3_CPSP_PREDECESSOR_SHA_PATCH_AUTHORIZED=1",
]
for token in required:
    assert token in text,token

s=rows(SUMMARY)
assert len(s)==14,len(s)
by={r["item"]:r for r in s}
for key in (
 "ELIGIBLE_HOUSEHOLDS_EXACTLY_ONE_REFERENCE",
 "ELIGIBLE_HOUSEHOLDS_BAD_REFERENCE_COUNT",
 "REFERENCE_PPPOS_41_MISMATCHES",
 "REPLICATE_RECORD_LENGTH_FAILURES",
 "MISSING_REFERENCE_REPLICATE_MATCHES",
 "HSUP_WGT_MARSUPWT_MISMATCHES",
 "PWWGT0_MARSUPWT_PRECISION_MISMATCHES",
 "PWWGT0_MARSUPWT_MAX_ABS_DIFF_1E4_UNITS",
 "PWWGT0_OFFICIAL_SUM",
):
    assert by[key]["gate"]=="PASS",(key,by[key])

assert by["ELIGIBLE_HOUSEHOLDS_BAD_REFERENCE_COUNT"]["observed"]=="0"
assert by["REFERENCE_PPPOS_41_MISMATCHES"]["observed"]=="0"
assert by["REPLICATE_RECORD_LENGTH_FAILURES"]["observed"]=="0"
assert by["MISSING_REFERENCE_REPLICATE_MATCHES"]["observed"]=="0"
assert by["HSUP_WGT_MARSUPWT_MISMATCHES"]["observed"]=="0"
assert by["PWWGT0_MARSUPWT_PRECISION_MISMATCHES"]["observed"]=="0"
assert int(by["PWWGT0_MARSUPWT_MAX_ABS_DIFF_1E4_UNITS"]["observed"])<=50
assert by["PWWGT0_OFFICIAL_SUM"]["observed"]=="MATCH"

print("CPSB_RUNTIME_AUDIT_SHA256="+hashlib.sha256(AUDIT.read_bytes()).hexdigest())
print("CPSB_RUNTIME_SUMMARY_SHA256="+hashlib.sha256(SUMMARY.read_bytes()).hexdigest())
print("CPSB_SUMMARY_ROWS=14")
print("CPS_MAIN_WEIGHT_VALUES_PARSED=1")
print("CPS_PWWGT0_VALUES_PARSED=1")
print("CPS_PWWGT1_160_VALUES_PARSED=0")
print("CPS_I_VALUES_READ=0")
print("CPS_WEIGHT_BRIDGE_EMPIRICALLY_TESTED=1")
print("OUTCOME_BASED_GATE=0")
print("SCIENTIFIC_METHOD_MUTATED=0")
print("NEXT_PRIMARY_PHASE_ID=E4D1D3_CPSP")
print("E4D1D3_CPSP_PREDECESSOR_SHA_PATCH_AUTHORIZED=1")
print("CPS_I_VALUE_OPEN_AUTHORIZED=0")
print("SCF_K_VALUE_OPEN_AUTHORIZED=0")
print("SCF_D_VALUE_OPEN_AUTHORIZED=0")
print("TEMPORAL_GEOMETRY_AUTHORIZED=0")
print("REAL_INFLATION_ESTIMATION_AUTHORIZED=0")
print("E4D1D3_CPSB_R0_POST_EXECUTION_VALIDATOR=PASS")
